user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8123;

        location / {

            # Allow host machine via Docker bridge (default gateway)
            allow 172.30.0.1;

            # Yandex DataLens whitelist
            allow 178.154.242.176/28;
            allow 178.154.242.192/28;
            allow 178.154.242.208/28;
            allow 178.154.242.128/28;
            allow 178.154.242.144/28;
            allow 178.154.242.160/28;
            allow 130.193.60.0/28;

            # Default deny for all others
            deny all;

            proxy_pass http://clickhouse:8123;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
